### ISSUE TITLE
Enabling / Disabling Beam.pro Crashes Program

### ISSUE THREAD

**Issue by Draygera** [xedoc/Ubiquitous2#6]
After reinstalling ubiquitous and windows 8.1, I had trouble getting beam.pro to work without crashing, especially when enabling it last. I've had it crash on turning it off a few times too. I've also noticed that the program will randomly crash for no reason later on, seemingly only when beam.pro is enabled.

Also, I hope I'm not getting annoying. :/

**Comment by xedoc** [comment]
Could you please check Event Viewer log for a Stack Trace ? I can't reproduce that issue on my PC.

**Comment by Draygera** [comment]
I'll have to wait until it crashes again. I forgot I had CCleaner on and it deleted all of my event logs. If it doesn't happen again within the next day or two, I'll close this issue out.

By the way, my PC specs:

4.0 Ghz AMD Athlon (3rd Gen) CPU
8GB DDR3 Kingston Hyper X Ram
Nvidia GeForce Gts 450 1 GB Gfx Card (with slightly older drivers since newest ones keep breaking my system)
2x 1 TB Western Digital HDD
1x 75 GB Seagate HDD (for Windows only)

I hope that these help a bit.

**Comment by Draygera** [comment]
It happened again earlier. Here are the two event logs from it:

Log Name:      Application
Source:        Application Error
Date:          7/17/2015 5:18:18 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      My-Shit
Description:
Faulting application name: Ubiquitous2.exe, version: 2.0.0.0, time stamp: 0x55a89b03
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0b99971c
Faulting process id: 0x1928
Faulting application start time: 0x01d0c0da793f2996
Faulting application path: C:\Users\Brandon\AppData\Local\Apps\2.0\VV5AE4EP.X5G\0HAQ8LV6.N21\ubiq..tion_1bba1ea0ead3dadc_0002.0002_87c8fc3cb15adfbe\Ubiquitous2.exe
Faulting module path: unknown
Report Id: b9aef286-2cd1-11e5-8266-408d5c00d7d7
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-07-17T22:18:18.000000000Z" />
    <EventRecordID>3342</EventRecordID>
    <Channel>Application</Channel>
    <Computer>My-Shit</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Ubiquitous2.exe</Data>
    <Data>2.0.0.0</Data>
    <Data>55a89b03</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>0b99971c</Data>
    <Data>1928</Data>
    <Data>01d0c0da793f2996</Data>
    <Data>C:\Users\Brandon\AppData\Local\Apps\2.0\VV5AE4EP.X5G\0HAQ8LV6.N21\ubiq..tion_1bba1ea0ead3dadc_0002.0002_87c8fc3cb15adfbe\Ubiquitous2.exe</Data>
    <Data>unknown</Data>
    <Data>b9aef286-2cd1-11e5-8266-408d5c00d7d7</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          7/17/2015 5:18:16 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      My-Shit
Description:
Application: Ubiquitous2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at UB.Model.ConnectcastChannel.<Join>b__1f()
   at UB.Model.WebSocketBase.socket_Opened(System.Object, System.EventArgs)
   at WebSocket4Net.WebSocket.OnHandshaked()
   at WebSocket4Net.Command.Handshake.ExecuteCommand(WebSocket4Net.WebSocket, WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.ExecuteCommand(WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[], Int32, Int32)
   at WebSocket4Net.WebSocket.client_DataReceived(System.Object, SuperSocket.ClientEngine.DataEventArgs)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[], Int32, Int32)
   at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(System.Net.Sockets.SocketAsyncEventArgs)
   at SuperSocket.ClientEngine.AsyncTcpSession.SocketEventArgsCompleted(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-07-17T22:18:16.000000000Z" />
    <EventRecordID>3341</EventRecordID>
    <Channel>Application</Channel>
    <Computer>My-Shit</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Ubiquitous2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at UB.Model.ConnectcastChannel.&lt;Join&gt;b__1f()
   at UB.Model.WebSocketBase.socket_Opened(System.Object, System.EventArgs)
   at WebSocket4Net.WebSocket.OnHandshaked()
   at WebSocket4Net.Command.Handshake.ExecuteCommand(WebSocket4Net.WebSocket, WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.ExecuteCommand(WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[], Int32, Int32)
   at WebSocket4Net.WebSocket.client_DataReceived(System.Object, SuperSocket.ClientEngine.DataEventArgs)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[], Int32, Int32)
   at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(System.Net.Sockets.SocketAsyncEventArgs)
   at SuperSocket.ClientEngine.AsyncTcpSession.SocketEventArgsCompleted(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
</Data>
  </EventData>
</Event>

**Comment by xedoc** [comment]
That was Connectcast. Should be fixed now.

**Comment by Draygera** [comment]
Ok. Will check out in a sec.

**Comment by Draygera** [comment]
Ok, I just did an 11 hour stream with no issues whatsoever (other than some random dropping of viewers; not a big deal). I'll go ahead and close this issue. Thanks for fixing it so quickly. XD
